# Generated by Django 2.1.7 on 2019-02-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usser',
            name='score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
