# Generated by Django 2.1.7 on 2019-02-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premier', '0002_usser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='week_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
